<?php
/**
 * @file
 * vrc_documentation.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function vrc_documentation_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Communicate & Collaborate',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '001c8790-a0cf-4858-9284-ed4e137c34e4',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Advanced',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '021ddefc-82e4-9c84-590e-6122e40e9595',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Anonymization',
    'description' => 'Most commentary on the Internet is essentially done anonymously, using unidentifiable pseudonyms. While these names can take on an identity of their own, they are frequently separated from and anonymous from the actual author, and according to the University of Stockholm creating more freedom of expression, and less accountability.',
    'format' => 'plain_text',
    'weight' => '9',
    'uuid' => '05cafae6-31b5-ce94-0d07-2b547b4a61d8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Connection (HTTPS,...)',
    'description' => 'Communication protocols and tips to ensure the security of a network connection.',
    'format' => 'plain_text',
    'weight' => '7',
    'uuid' => '06688f39-5324-4762-a2dc-8a32ae8c28de',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Training Tools',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '082c8eb0-ef99-4ec9-a6b2-99839ed7713f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Protect yourself',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '08ed727b-6fa9-4a11-9e5d-be0868ef4125',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Web Administration',
    'description' => 'All advices and tools for managing a website, whatever its size, whatever its format.',
    'format' => 'plain_text',
    'weight' => '9',
    'uuid' => '0a30fd30-951a-f1a4-d949-56f70679a9e1',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Protect yourself',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '0a9483c7-b655-7084-0d76-e6c97b9949ac',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Browsing tools',
    'description' => 'Browsers, plugins and modules, advices on configuration and best practices.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '0f233fd3-2d81-2ed4-89c5-7cdd04d44150',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'System Administration',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '106ded14-17ef-23f4-49be-ffe8a520f89e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Safety',
    'description' => 'General tips on safety in the digital age.',
    'format' => 'plain_text',
    'weight' => '10',
    'uuid' => '11535592-ef18-d9b4-e11b-c2581bf529f9',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Anonymization',
    'description' => 'Most commentary on the Internet is essentially done anonymously, using unidentifiable pseudonyms. While these names can take on an identity of their own, they are frequently separated from and anonymous from the actual author, and according to the University of Stockholm creating more freedom of expression, and less accountability.',
    'format' => NULL,
    'weight' => '9',
    'uuid' => '123deea2-60cd-da64-f9d5-c2da4eb2b401',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Journalism',
    'description' => 'Tools and resources for journalists and citizen journalists',
    'format' => NULL,
    'weight' => '4',
    'uuid' => '140e805f-6198-4ab4-1982-d3c26979e1d8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'System Administration',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '141dc549-69a8-4766-a6d2-5319050c68a8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Connection (HTTPS,...)',
    'description' => 'Communication protocols and tips to ensure the security of a network connection.',
    'format' => 'plain_text',
    'weight' => '7',
    'uuid' => '18f6985c-ff5e-5364-6da9-0c0c5e434345',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Safety',
    'description' => 'General tips on safety in the digital age.',
    'format' => 'plain_text',
    'weight' => '10',
    'uuid' => '1d2156dc-6f52-4f79-99b3-82bd098ad7e4',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Mobile Technology',
    'description' => 'Mobile technology is a collective term used to describe the various types of cellular communication technology',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '1d437bcf-d2e1-4d7e-bb19-951637a8bc4d',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Team Collaboration',
    'description' => 'Project teams today move faster and work under more pressure than ever before. To expedite information sharing and to accelerate decision making, project managers are using team collaboration tools.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '1e50bf7e-86cb-4224-b190-2affb8d51e60',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Circumvention',
    'description' => 'Internet censorship circumvention is the process used by technologically savvy Internet users to bypass the technical aspects of Internet filtering and gain access to otherwise censored material.',
    'format' => NULL,
    'weight' => '2',
    'uuid' => '220b963b-213a-0024-e9f3-8860009915ba',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'eLearning',
    'description' => 'E-learning includes all forms of electronically supported learning and teaching. E-learning applications and processes include Web-based learning, computer-based learning, virtual education opportunities and digital collaboration.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '2331014a-ff9c-45f4-bd4d-8459f9e306df',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Multimedia tools',
    'description' => 'Everything related to the publication and distribution of multimedia content, from video, audio to photo processing.',
    'format' => 'plain_text',
    'weight' => '6',
    'uuid' => '2c005004-6731-4f04-beef-98bea197297e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Offline Browsing',
    'description' => 'An offline reader (sometimes called an offline browser or offline navigator) is computer software that downloads e-mail, newsgroup posts or web pages, making them available when the computer is offline: not connected to the Internet or, in the late 20th century, bulletin board systems. Offline readers are useful for portable computers and dial-up access.',
    'format' => NULL,
    'weight' => '3',
    'uuid' => '2e12517d-a1f6-9dc4-0594-47b2a5fd0064',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Anonymization',
    'description' => 'Most commentary on the Internet is essentially done anonymously, using unidentifiable pseudonyms. While these names can take on an identity of their own, they are frequently separated from and anonymous from the actual author, and according to the University of Stockholm creating more freedom of expression, and less accountability.',
    'format' => 'plain_text',
    'weight' => '9',
    'uuid' => '2e912194-423b-46e9-9f1b-89672b933c50',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure System (Anti-Virus, Malware,...)',
    'description' => 'Define a set of tools and software used to prevent, detect and remove malware, such as: computer viruses, adware, backdoors, malicious BHOs, dialers, fraudtools, hijackers, keyloggers, malicious LSPs, rootkits, spyware, trojan horses and worms. Computer security, including protection from social engineering techniques, is commonly offered in products and services of antivirus software companies. ',
    'format' => NULL,
    'weight' => '8',
    'uuid' => '319f6a35-7c07-1974-6d93-17ea3fce068a',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Circumvention',
    'description' => 'Internet censorship circumvention is the process used by technologically savvy Internet users to bypass the technical aspects of Internet filtering and gain access to otherwise censored material.',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => '3417c075-eece-4700-9129-1e96934483ef',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Connection (HTTPS,...)',
    'description' => 'Communication protocols and tips to ensure the security of a network connection.',
    'format' => NULL,
    'weight' => '7',
    'uuid' => '38937925-7a6e-3174-694d-05e55b7a0d6f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Browsing tools',
    'description' => 'Browsers, plugins and modules, advices on configuration and best practices.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '3a1895bd-75c2-4a92-a4bd-b01b7b5b1329',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Password',
    'description' => 'Tips and techniques for password management',
    'format' => 'plain_text',
    'weight' => '4',
    'uuid' => '3a7e019e-37d2-46bb-84db-726941277f4e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Social Media',
    'description' => 'Social media includes web- and mobile-based technologies which are used to turn communication into interactive dialogue among organizations, communities, and individuals. ',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => '40e73eae-e5ed-4401-a780-da8cdeab8da0',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Promotion',
    'description' => 'Promoting services or websites online.',
    'format' => 'plain_text',
    'weight' => '5',
    'uuid' => '44c799d5-32a6-4fa3-b33a-62fbb6832bd9',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Journalism',
    'description' => 'Tools and resources for journalists and citizen journalists',
    'format' => 'plain_text',
    'weight' => '4',
    'uuid' => '4536983a-882b-3164-3d31-d335b95dfaf8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Data (Encryption,...)',
    'description' => 'The techniques and protocols that can be use to encrypt data into ones computer.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '4816eeab-17ac-39b4-4da5-9ff66bf37ba3',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Training Tools',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '497651d5-2ae3-24f4-a5de-f78f418aaaf7',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Basics',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4d12fd3f-19e0-9714-d501-11f546e79a41',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Web security',
    'description' => 'Web Security',
    'format' => 'plain_text',
    'weight' => '8',
    'uuid' => '4d7a1dfc-affb-4a59-90cc-fdd68312560a',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Publish & Share',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '528b318a-5694-8134-1160-f44681261a89',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Mobile Security',
    'description' => 'Mobile security or mobile phone security has become increasingly important in mobile computing. It is of particular concern as it relates to the security of personal information now stored on smartphones.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '560e19b6-51f6-6b64-7947-087b12360585',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Offline Browsing',
    'description' => 'An offline reader (sometimes called an offline browser or offline navigator) is computer software that downloads e-mail, newsgroup posts or web pages, making them available when the computer is offline: not connected to the Internet or, in the late 20th century, bulletin board systems. Offline readers are useful for portable computers and dial-up access.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '59311d56-2d17-6a14-951c-581b4e93914b',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Journalism, Safety',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5a95ea12-f8cd-47a4-f5bf-6db20d6af9c4',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Inform & Engage',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '5bd5cd76-d537-9a24-e505-99a00da93b65',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Inform & Engage',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '6b134236-6a5b-46af-b7c6-b30507db9296',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Community Mobilization',
    'description' => 'Community mobilization is an attempt to bring both human and non-human resources together to undertake developmental activities in order to achieve sustainable development.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '6c0bc745-11d9-45b4-9b26-c9a15d6dc976',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Communicate & Collaborate',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '6f4576c7-e94c-1694-611f-ed23b5053104',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Design & Visualisation',
    'description' => 'Data visualization is the study of the visual representation of data, meaning "information that has been abstracted in some schematic form, including attributes or variables for the units of information',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '6fbf59d1-6d28-6614-c1c6-fbfa71725ec9',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Computer Basics',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '72db71e8-c40c-6874-494a-824e39cab76f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Hosting',
    'description' => 'Articles and resources on security aspects of web hosting. Includes Ddos protection layer, SSL certificates, etc...',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => '79569a77-38fa-c254-b544-29f9cf07b692',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Communications (Enigmail,OTR,...)',
    'description' => 'Tools and techniques for secure communication',
    'format' => NULL,
    'weight' => '6',
    'uuid' => '7ca4e618-1ebf-9584-8999-1601875ce2eb',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Access to information',
    'description' => 'Resources on technologies that will allow users to access information online or offline',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '7e5fad1f-8a09-4108-944e-ac42633d90b6',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Basics',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => '80fd18c0-32c1-8a14-e5e7-3032ddba27d7',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Content Management System',
    'description' => 'A content management system (CMS) is a computer system that allows publishing, editing, and modifying content as well as site maintenance from a central page. It provides a collection of procedures used to manage workflow in a collaborative environment. These procedures can be manual or computer-based.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '815b190b-0f2d-9fb4-c576-6ebce5f08a18',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Publish & Share',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '853e3a89-cb28-8324-d5d1-ed5aa904c3e5',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Web security',
    'description' => 'Web Security',
    'format' => 'plain_text',
    'weight' => '8',
    'uuid' => '85fe41a8-d68d-4294-5546-d3dc9806092c',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Team Collaboration',
    'description' => 'Project teams today move faster and work under more pressure than ever before. To expedite information sharing and to accelerate decision making, project managers are using team collaboration tools.',
    'format' => NULL,
    'weight' => '3',
    'uuid' => '88a455c4-17f0-3344-cd5d-82ab634063d7',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Promotion',
    'description' => 'Promoting services or websites online.',
    'format' => 'plain_text',
    'weight' => '5',
    'uuid' => '8e197b25-2310-b774-7127-4e557acf824e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Data (Encryption,...)',
    'description' => 'The techniques and protocols that can be use to encrypt data into ones computer.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => '914a3639-d2e1-41c9-aff3-2f3f98bf7556',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Offline Browsing',
    'description' => 'An offline reader (sometimes called an offline browser or offline navigator) is computer software that downloads e-mail, newsgroup posts or web pages, making them available when the computer is offline: not connected to the Internet or, in the late 20th century, bulletin board systems. Offline readers are useful for portable computers and dial-up access.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => '919ac30f-a696-42fa-9a83-be43746fd606',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Data Collection',
    'description' => 'Data collection is a term used to describe a process of preparing and collecting data. The purpose of data collection is to obtain information to keep on record, to make decisions about important issues, or to pass information on to others. Data are primarily collected to provide information regarding a specific topic.',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => '91f39ddf-33e5-aac4-a180-4473eed61cdf',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Access to information',
    'description' => 'Resources on technologies that will allow users to access information online or offline',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '93d65289-c7ce-aff4-49c9-b028e96b4ffc',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Hosting',
    'description' => 'Articles and resources on security aspects of web hosting. Includes Ddos protection layer, SSL certificates, etc...',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => '9b279976-8693-4add-9785-82331f61ee81',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Communicate & Collaborate',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9bc4ff42-3ce7-d0d4-41bf-472834eb961c',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Internet Basics',
    'description' => 'Basic internet skills',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'a1a3adc0-abd3-4b04-bf83-b819a27c44a6',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Internet Basics',
    'description' => 'Basic internet skills',
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'a1ef5e14-27fc-9014-6d03-5ba3fdfbf79d',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Team Collaboration',
    'description' => 'Project teams today move faster and work under more pressure than ever before. To expedite information sharing and to accelerate decision making, project managers are using team collaboration tools.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => 'a53bdec7-969a-0664-215c-94b4428d8bc0',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'System Administration',
    'description' => '',
    'format' => NULL,
    'weight' => '3',
    'uuid' => 'a5b50481-1907-f874-a9b6-c48b0aea7040',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Mobile Technology',
    'description' => 'Mobile technology is a collective term used to describe the various types of cellular communication technology',
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'a83d5b85-3480-19e4-1d77-09aa74127281',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Mobile Security',
    'description' => 'Mobile security or mobile phone security has become increasingly important in mobile computing. It is of particular concern as it relates to the security of personal information now stored on smartphones.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => 'aad7742f-e194-41a9-866f-9a410d03e4ac',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Browsing tools',
    'description' => 'Browsers, plugins and modules, advices on configuration and best practices.',
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'ac04ebfd-f7eb-c714-1136-9fe6e711f5ab',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Journalism',
    'description' => 'Tools and resources for journalists and citizen journalists',
    'format' => 'plain_text',
    'weight' => '4',
    'uuid' => 'aef07534-8b59-40ea-a813-30d8129d4ed2',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Multimedia tools',
    'description' => 'Everything related to the publication and distribution of multimedia content, from video, audio to photo processing.',
    'format' => 'plain_text',
    'weight' => '6',
    'uuid' => 'b12a30b5-8e16-9ce4-f5e0-2dd71b963d3d',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Software Engineering',
    'description' => 'oftware engineering (SE) is the application of a systematic, disciplined, quantifiable approach to the design, development, operation, and maintenance of software, and the study of these approaches; that is, the application of engineering to software.',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'bc40ce6c-13ed-c484-3dfd-27de81aaad48',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Publish & Share',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'be2686af-677e-4c02-946f-241458625c0d',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Monetization',
    'description' => 'Resources on how do you make money out of your online activities.',
    'format' => 'plain_text',
    'weight' => '5',
    'uuid' => 'bed6e5ca-f17f-43b8-ae74-c58edbe4b05c',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Social Media',
    'description' => 'Social media includes web- and mobile-based technologies which are used to turn communication into interactive dialogue among organizations, communities, and individuals. ',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'bf4487b2-1586-65e4-71f3-c0d6bded68a3',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Communications (Enigmail,OTR,...)',
    'description' => 'Tools and techniques for secure communication',
    'format' => 'plain_text',
    'weight' => '6',
    'uuid' => 'c1131374-2130-eec4-cd62-2ed7c257da4e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Social Media',
    'description' => 'Social media includes web- and mobile-based technologies which are used to turn communication into interactive dialogue among organizations, communities, and individuals. ',
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'c15f8d7e-419b-83d4-51b3-b2ae39dd46fd',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Office tools',
    'description' => 'Office suite or productivity suite.',
    'format' => 'plain_text',
    'weight' => '7',
    'uuid' => 'c25f3150-23d9-4465-a776-0e11ed9eb13e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Community Mobilization',
    'description' => 'Community mobilization is an attempt to bring both human and non-human resources together to undertake developmental activities in order to achieve sustainable development.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => 'c28f3e27-c2a1-4a04-7dbf-711760674e24',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Software Engineering',
    'description' => 'oftware engineering (SE) is the application of a systematic, disciplined, quantifiable approach to the design, development, operation, and maintenance of software, and the study of these approaches; that is, the application of engineering to software.',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'c4fd6a36-1b2d-4054-b393-f04298055fdd',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Software Engineering',
    'description' => 'oftware engineering (SE) is the application of a systematic, disciplined, quantifiable approach to the design, development, operation, and maintenance of software, and the study of these approaches; that is, the application of engineering to software.',
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'c7badc7e-5565-0b44-090b-90e29ec90240',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Office tools',
    'description' => 'Office suite or productivity suite.',
    'format' => 'plain_text',
    'weight' => '7',
    'uuid' => 'c8b86601-33d3-6eb4-f9df-91c59fa01116',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Safety',
    'description' => 'General tips on safety in the digital age.',
    'format' => NULL,
    'weight' => '10',
    'uuid' => 'c9d6ee69-db2f-7c64-59a7-adee94d76aa4',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Advanced',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c9dff692-c166-e194-2d3d-8b425761836c',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Circumvention',
    'description' => 'Internet censorship circumvention is the process used by technologically savvy Internet users to bypass the technical aspects of Internet filtering and gain access to otherwise censored material.',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'ca22ec36-0915-1914-1144-b01dadaebfd6',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Promotion',
    'description' => 'Promoting services or websites online.',
    'format' => NULL,
    'weight' => '5',
    'uuid' => 'ca74f81d-f52f-b9f4-0116-d68ee9de4845',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Protect yourself',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cc278100-c606-1484-bde8-85d3b32dbf23',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Basics',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'ce705eee-67e7-4b5a-ab26-759f7f986d70',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Data Collection',
    'description' => 'Data collection is a term used to describe a process of preparing and collecting data. The purpose of data collection is to obtain information to keep on record, to make decisions about important issues, or to pass information on to others. Data are primarily collected to provide information regarding a specific topic.',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'cf3e2e3b-a5c3-4dd8-a182-4fb3f8e847fd',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure System (Anti-Virus, Malware,...)',
    'description' => 'Define a set of tools and software used to prevent, detect and remove malware, such as: computer viruses, adware, backdoors, malicious BHOs, dialers, fraudtools, hijackers, keyloggers, malicious LSPs, rootkits, spyware, trojan horses and worms. Computer security, including protection from social engineering techniques, is commonly offered in products and services of antivirus software companies. ',
    'format' => 'plain_text',
    'weight' => '8',
    'uuid' => 'd5e113a9-c19b-47ab-aac0-d15f05712c96',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Computer Basics',
    'description' => '',
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'db02f8fd-1809-3274-69e3-542c287d27fe',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Web Administration',
    'description' => 'All advices and tools for managing a website, whatever its size, whatever its format.',
    'format' => 'plain_text',
    'weight' => '9',
    'uuid' => 'dc6b7fd6-dbb7-46c9-9f25-ed5fd529e0c2',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Communications (Enigmail,OTR,...)',
    'description' => 'Tools and techniques for secure communication',
    'format' => 'plain_text',
    'weight' => '6',
    'uuid' => 'dd83f244-eba8-4a49-9b4c-1ef2bcd95dbf',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Computer Basics',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => 'de7e864b-53de-43d5-ac2b-db0bcaa24eee',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Access to information',
    'description' => 'Resources on technologies that will allow users to access information online or offline',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'de9e4e49-dbf5-0904-65de-6cfe78238abb',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Design & Vizualisation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e0788b48-f397-7ea4-a1c0-520b0d7803e8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Mobile Technology',
    'description' => 'Mobile technology is a collective term used to describe the various types of cellular communication technology',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => 'e09faef2-d3c5-c304-dd78-7156ae8d4644',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Web security',
    'description' => 'Web Security',
    'format' => NULL,
    'weight' => '8',
    'uuid' => 'e533141b-40ac-e4e4-25b8-2a029782da4f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Secure System (Anti-Virus, Malware,...)',
    'description' => 'Define a set of tools and software used to prevent, detect and remove malware, such as: computer viruses, adware, backdoors, malicious BHOs, dialers, fraudtools, hijackers, keyloggers, malicious LSPs, rootkits, spyware, trojan horses and worms. Computer security, including protection from social engineering techniques, is commonly offered in products and services of antivirus software companies. ',
    'format' => 'plain_text',
    'weight' => '8',
    'uuid' => 'e5be1340-7f0d-a124-51e5-9689da67650e',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'eLearning',
    'description' => 'E-learning includes all forms of electronically supported learning and teaching. E-learning applications and processes include Web-based learning, computer-based learning, virtual education opportunities and digital collaboration.',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => 'e62c6146-e356-4f46-a295-52173b9e7550',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Inform & Engage',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e6dffc79-35e9-9814-adf6-663ebfcec2d2',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Internet Basics',
    'description' => 'Basic internet skills',
    'format' => 'plain_text',
    'weight' => '2',
    'uuid' => 'e8a2b07b-674b-92c4-75d0-65d08ef85fe8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Design & Visualisation',
    'description' => 'Data visualization is the study of the visual representation of data, meaning "information that has been abstracted in some schematic form, including attributes or variables for the units of information',
    'format' => 'plain_text',
    'weight' => '3',
    'uuid' => 'e9d34224-a7fc-462e-be84-25e7a14702e3',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Content Management System',
    'description' => 'A content management system (CMS) is a computer system that allows publishing, editing, and modifying content as well as site maintenance from a central page. It provides a collection of procedures used to manage workflow in a collaborative environment. These procedures can be manual or computer-based.',
    'format' => 'plain_text',
    'weight' => '1',
    'uuid' => 'edb99f33-19ae-44d5-9366-c45adc13ede5',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Password',
    'description' => 'Tips and techniques for password management',
    'format' => 'plain_text',
    'weight' => '4',
    'uuid' => 'ee375162-a3ad-2d34-75cd-5faf9a86a91f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Advanced',
    'description' => '',
    'format' => 'plain_text',
    'weight' => '0',
    'uuid' => 'f3b8e709-1626-4529-84d4-8bceda9b47ff',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Monetization',
    'description' => 'Resources on how do you make money out of your online activities.',
    'format' => 'plain_text',
    'weight' => '5',
    'uuid' => 'f63922bb-aa48-8624-81de-ede5785d3779',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  return $terms;
}
