<?php
/**
 * @file
 * vrc_tools_vocabulary.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function vrc_tools_vocabulary_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Apollo HQ',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '003281b1-b50f-86b4-e97c-a7988942a3b7',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'KeePass',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0262f3ea-a6c5-3a74-1d65-81336f6dc96d',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Tor',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '027f3172-4c90-ad74-2569-50cb16aab2b3',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Wuala',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '039ed672-ac64-c6a4-097c-ae8a2543e408',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Tails',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '047ce547-52fa-c8c4-49cd-36676c8be089',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Google Docs',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0530e901-f7c4-dd04-55cd-df778feb43ca',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Freegate',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '05b42e1f-5f50-9184-7d55-7f821c06de66',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'UltraSurf',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0fed26d4-6c58-4cb4-3926-555e4f9c4a16',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Vesuvio',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '10edb452-9e1a-3584-f1ce-f94807e73396',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Swara',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '11552fa0-7481-ff44-7df6-f6588fcc9534',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Permanent Eraser',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '11b518b5-2c00-c4b4-25d0-26980ecbda4a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Anonymization',
    'description' => 'Most commentary on the Internet is essentially done anonymously, using unidentifiable pseudonyms. While these names can take on an identity of their own, they are frequently separated from and anonymous from the actual author, and according to the University of Stockholm creating more freedom of expression, and less accountability.',
    'format' => NULL,
    'weight' => '9',
    'uuid' => '123deea2-60cd-da64-f9d5-c2da4eb2b401',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Your:Freedom',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '134124fa-b0eb-5a94-2183-a64950597552',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Tunnelblick',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '138cce1b-062d-8df4-1102-56759d9d0cf1',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Journalism',
    'description' => 'Tools and resources for journalists and citizen journalists',
    'format' => NULL,
    'weight' => '4',
    'uuid' => '140e805f-6198-4ab4-1982-d3c26979e1d8',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Orbot',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '16f1abb5-7039-a924-ad60-09f919a5fa0a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'TrueCrypt',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1abab7c1-2663-a744-c930-a033df2ad8ff',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Duck Duck Go',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1b0f934c-81a7-4a14-2173-98899caa221a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Circumvention',
    'description' => 'Internet censorship circumvention is the process used by technologically savvy Internet users to bypass the technical aspects of Internet filtering and gain access to otherwise censored material.',
    'format' => NULL,
    'weight' => '2',
    'uuid' => '220b963b-213a-0024-e9f3-8860009915ba',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'DNSCrypt',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '22f71105-60c4-8384-6113-bdce6d566b95',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'HotSpotShield',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2329a505-dbb6-5474-c504-aa46ab2f848d',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Google Trends',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '26ea28f4-547f-7094-31ce-7715dd03ca07',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Adbrite',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '28d4aa38-faef-d824-9141-41025dbd8b6b',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Jondo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '29a48b08-31d9-7c14-8596-62139f6d340a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'TextSecure',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2b096edc-6d45-fa64-4d05-03c16d63ac92',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'FoxyProxy',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2b24f690-3da4-88a4-09bc-46f90bd6da33',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'FreedomFone',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2b8f0e2c-f5e7-d5f4-29df-66b168b17ccf',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Offline Browsing',
    'description' => 'An offline reader (sometimes called an offline browser or offline navigator) is computer software that downloads e-mail, newsgroup posts or web pages, making them available when the computer is offline: not connected to the Internet or, in the late 20th century, bulletin board systems. Offline readers are useful for portable computers and dial-up access.',
    'format' => NULL,
    'weight' => '3',
    'uuid' => '2e12517d-a1f6-9dc4-0594-47b2a5fd0064',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Yodiz',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2e9e90c6-c9da-d764-81b4-92a2d4fd916f',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'GTunnel',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2f1291b6-289d-6464-c142-d9330e2028ac',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Fring',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2f8ef071-3fa6-b3c4-950f-d805545ea500',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Asana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '30af5cf6-5804-b264-b10f-5435cacbecb2',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Secure System (Anti-Virus, Malware,...)',
    'description' => 'Define a set of tools and software used to prevent, detect and remove malware, such as: computer viruses, adware, backdoors, malicious BHOs, dialers, fraudtools, hijackers, keyloggers, malicious LSPs, rootkits, spyware, trojan horses and worms. Computer security, including protection from social engineering techniques, is commonly offered in products and services of antivirus software companies. ',
    'format' => NULL,
    'weight' => '8',
    'uuid' => '319f6a35-7c07-1974-6d93-17ea3fce068a',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Google Fusion',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '33cd0b3a-efa9-a914-05dc-6190de0b6c34',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Connection (HTTPS,...)',
    'description' => 'Communication protocols and tips to ensure the security of a network connection.',
    'format' => NULL,
    'weight' => '7',
    'uuid' => '38937925-7a6e-3174-694d-05e55b7a0d6f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => '1Password',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3997e9a4-d2f0-1a34-e5ca-61510d714b0d',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'General',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3a50a985-233a-c384-0dd8-0ccd5c27e958',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'VPN',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3ddf1a74-9989-49b4-d507-7897e6b1fe35',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Dashlane',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3ecdda58-cf40-67d4-9504-aa9178f50460',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'RedPhone',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '44ba8fc2-ba34-7274-093c-adadaa5997df',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'MediaWiki',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4542a3ee-e783-abf4-a949-0e8422b6d09b',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Basics',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4d12fd3f-19e0-9714-d501-11f546e79a41',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Plumi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5084e45a-c2cf-50c4-c5a6-a4064fb61e96',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Spip',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '53e0ecf8-70be-c024-c541-852e03db933e',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Recuva',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '576984f3-fabd-5244-19e8-9de382bc1223',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Little Snitch',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '618cb6ea-6ffe-ac04-b5a4-23b91a439cf2',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'DoubleClick',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '665380c0-82cc-dee4-5dd6-b654a9557e33',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Drupal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '687e43bd-e477-6454-191c-ffe6cca9cddb',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Thunderbird with Enigmail and GPG',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6aae9fda-27f8-21f4-1d06-125e08c6fcee',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Priv3 Firefox Extension',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6b166278-03ff-aaf4-81e7-880cb435c7c4',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Ushahidi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6f174143-dc80-6f84-b59f-7bd009042af4',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'CiviCRM',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '71e41746-513a-2904-ad65-4224eb5bd13a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Expatshield',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7537c5c6-7c0b-f894-a162-ab3299716add',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Ghostery',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '75ceed6d-0ab0-3424-e9ae-745ecbb253a1',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Secure Communications (Enigmail,OTR,...)',
    'description' => 'Tools and techniques for secure communication',
    'format' => NULL,
    'weight' => '6',
    'uuid' => '7ca4e618-1ebf-9584-8999-1601875ce2eb',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Kiwix',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7dae934f-bd11-4bb4-ad21-62cd96edeaf7',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Gibberbot',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '816c0a07-e5c7-4f74-a942-ee1e807c7bce',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Google Analytics',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8269dae7-ba5e-2c94-0116-5c2f1f8c8bee',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Basecamp',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '84870880-446c-5de4-598f-c9b95d546cd7',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Publish & Share',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '853e3a89-cb28-8324-d5d1-ed5aa904c3e5',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Team Collaboration',
    'description' => 'Project teams today move faster and work under more pressure than ever before. To expedite information sharing and to accelerate decision making, project managers are using team collaboration tools.',
    'format' => NULL,
    'weight' => '3',
    'uuid' => '88a455c4-17f0-3344-cd5d-82ab634063d7',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Google Moderator',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '896fb774-54ad-65b4-ed71-ff5508280fba',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'OpenVPN',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '897a0085-6b8c-b9e4-b59d-10a78eb79274',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'HTTPS Everywhere',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '89bf5990-4412-7a84-bdf4-916dfcdfc90a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'OpenOffice',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8bf2f824-dbe3-6334-9d7b-fe5f0fce055f',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Wickr',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8d27c6ac-fe52-2654-b979-bcc6ca4a9aa2',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Thunderbird',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8da25e68-0788-1494-e1a8-021e201be848',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Psiphon',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8e81e43a-a876-2044-115e-3c54dcfdfa1d',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Frontline SMS',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8fde1cee-40e7-7b14-5523-898ac9bd1fb5',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Sophos AntiVirus',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '90ac6f04-810c-74c4-bdeb-d7551de19f57',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'LastPass',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '91763e68-afd2-5254-393b-ce1ddea616b8',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Access to information',
    'description' => 'Resources on technologies that will allow users to access information online or offline',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '93d65289-c7ce-aff4-49c9-b028e96b4ffc',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'K-9 Mail',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '97b0b726-94e8-d224-7d1c-075736484856',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Eden',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9a7e4fb4-9847-a0d4-7d7d-34f712c7c0f1',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Lookout Mobile Security',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9b568a6d-9745-5574-ed75-f14b80c41139',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Communicate & Collaborate',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9bc4ff42-3ce7-d0d4-41bf-472834eb961c',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Gimp',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9c34ce41-9b2f-eec4-b52d-d2e1446dde0e',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'WhisperMonitor',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9d3e2f2f-0c18-e0b4-49ab-8dfe65ab6b1f',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'SecurityKiss',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e7d7fa8-5ac6-6524-4d6b-64fd6b521fb1',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Internet Basics',
    'description' => 'Basic internet skills',
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'a1ef5e14-27fc-9014-6d03-5ba3fdfbf79d',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'OpenAtrium',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a4105868-a8a4-3f24-3d86-4169baecb670',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'System Administration',
    'description' => '',
    'format' => NULL,
    'weight' => '3',
    'uuid' => 'a5b50481-1907-f874-a9b6-c48b0aea7040',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Google Ads',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a82e1078-2ccd-d0b4-f5fe-dab7a5262fc2',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Mobile Technology',
    'description' => 'Mobile technology is a collective term used to describe the various types of cellular communication technology',
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'a83d5b85-3480-19e4-1d77-09aa74127281',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Avira',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a8cd5b4c-e3d7-ef24-dda9-a0e9366f2228',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Browsing tools',
    'description' => 'Browsers, plugins and modules, advices on configuration and best practices.',
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'ac04ebfd-f7eb-c714-1136-9fe6e711f5ab',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Avidemux',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b066f56c-7786-e704-21a2-7f8a6c0888a4',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Tableau Public',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b73930c2-f9b8-a034-197b-fa0c4b6ff078',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'GPass',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b74bbd69-5eed-7214-318f-e2b1e9ad0a03',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Twitter',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b8501a1c-0289-1734-f968-79ce47db14b8',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'KL Detector',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b93eeeb7-3e00-5674-1155-c05dae8a7d70',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Vumi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bb902667-2e19-dc54-1d32-ae0a40b9a1fe',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'PhotoME',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'be588a88-fbc8-1074-6dae-f97b71fea2e4',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Technitium Mac Address Changer',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c07df7d1-d1d6-3514-7560-33e6e6b1683d',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Social Media',
    'description' => 'Social media includes web- and mobile-based technologies which are used to turn communication into interactive dialogue among organizations, communities, and individuals. ',
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'c15f8d7e-419b-83d4-51b3-b2ae39dd46fd',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'PrivateGSM',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c49350a6-52d6-e664-3995-5b6c1b42aa5a',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Software Engineering',
    'description' => 'oftware engineering (SE) is the application of a systematic, disciplined, quantifiable approach to the design, development, operation, and maintenance of software, and the study of these approaches; that is, the application of engineering to software.',
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'c7badc7e-5565-0b44-090b-90e29ec90240',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Simurgh',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c838a814-5773-5184-a10b-53395b971b85',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Jira',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c8f5f8d2-13d3-d274-a98b-d35e4cfcc493',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Safety',
    'description' => 'General tips on safety in the digital age.',
    'format' => NULL,
    'weight' => '10',
    'uuid' => 'c9d6ee69-db2f-7c64-59a7-adee94d76aa4',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Advanced',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c9dff692-c166-e194-2d3d-8b425761836c',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Promotion',
    'description' => 'Promoting services or websites online.',
    'format' => NULL,
    'weight' => '5',
    'uuid' => 'ca74f81d-f52f-b9f4-0116-d68ee9de4845',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'SabzProxy',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cafe6da7-7c19-3614-8510-afcf36c2cb27',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Protect yourself',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cc278100-c606-1484-bde8-85d3b32dbf23',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'TileMill',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ce194db5-8919-6994-6da0-2a8c424910c5',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Audacity',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd3d46d7a-7a11-db54-894a-ec1c759b3a50',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Yahoo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd4013fc5-071a-3d84-c9c6-447188b5246c',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Avast!',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd40ceb09-60dc-a0b4-1132-69bbf14c244f',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'LibreOffice',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd8912b3f-d1c2-2484-4df9-7e18a0122868',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Firefox',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd908ed71-c116-bdd4-bdad-cf1c48b09dd0',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Computer Basics',
    'description' => '',
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'db02f8fd-1809-3274-69e3-542c287d27fe',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Trac',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dc70787f-847d-efa4-595f-2be508045a35',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Cryptocat',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dd08f7a1-3e71-16f4-8d51-ecfa289e461e',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Commossion Wireless',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dff2432a-89ac-6d24-0dbe-f41b98918210',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'activeCollab',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e0e0d7ff-fcbc-7c94-7520-0f536eb871bf',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Alkasir',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e4a55279-c0ed-a624-f1c0-be5029af4fc0',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'WhisperCore',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e51ce28a-b9ba-a284-b5f3-b36cb864538b',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Web security',
    'description' => 'Web Security',
    'format' => NULL,
    'weight' => '8',
    'uuid' => 'e533141b-40ac-e4e4-25b8-2a029782da4f',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'CCleaner',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e5fcd754-703d-be94-cd3a-e47d4e7531af',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Inform & Engage',
    'description' => '',
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e6dffc79-35e9-9814-adf6-663ebfcec2d2',
    'vocabulary_machine_name' => 'taxonomy_categories',
    'field_guid' => array(),
    'field_synonym' => array(),
  );
  $terms[] = array(
    'name' => 'Pidgin with OTR',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e766d9d9-43dd-d514-d922-097f82016d0d',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Facebook',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ee02525a-25dc-4514-25d3-ba5b0d7d8b6c',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'GeoChat',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eeae6551-75cd-1ee4-c968-efd935860526',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Flashback',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f4a2916f-e3a4-77d4-65dc-c96833cd3f4c',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Wordpress',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f65fdddb-af0e-1914-716b-88d68cd43cf7',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Kino',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f747fa48-664a-1484-f11b-6c89e10acede',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Obscuracam',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f87c83ff-1db0-e8a4-1d1c-2397c34c8a09',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Piwik',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f9dd3dcb-cc31-5b64-6d65-e1b4bea76086',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  $terms[] = array(
    'name' => 'Moodle',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fcb9e483-fabc-cca4-0d1f-8e05235aa667',
    'vocabulary_machine_name' => 'tool',
    'field_toolbox_categories' => array(),
  );
  return $terms;
}
